### ISSUE TITLE
Use in TouchGFX

### ISSUE THREAD

**Issue by arghashi** [STMicroelectronics/stm32-gt911#1]
Hello and respect
Is it possible to provide a sample code to be used in TouchGFX??

**Comment by ALABSTM** [comment]
Hi @arghashi,

Thank you for your question. The _GT911_ touch screen controller is used on the two boards below:
* [STM32U5G9J-DK2](https://www.st.com/en/evaluation-tools/stm32u5g9j-dk2.html)
* [STM32H7S78-DK](https://www.st.com/en/evaluation-tools/stm32h7s78-dk.html)

There is currently no demo of how to use _TouchGFX_ with the _GT911_ driver in the firmware of neither series. However:
* You can generate the source code of a complete demo using the [TouchGFX Designer](https://www.st.com/en/development-tools/touchgfxdesigner.html).
* You can also find a sample code [here](https://github.com/STMicroelectronics/stm32u5g9j-dk2-bsp/blob/d16bd738ae60565c5ad6957c65e833269734cb99/stm32u5g9j_discovery_ts.c) that you may find helpful.

By the way, if you have questions about the _TouchGFX Designer_, you can ask them [here](https://community.st.com/t5/stm32-mcus-touchgfx-and-gui/bd-p/mcu-touch-gfx-gui-forum).

With regards,

**Comment by arghashi** [comment]
Thank you very much, your advice helped me a lot.
